# Generated by Django 5.2.5 on 2025-08-07 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('yellow_card', 'Yellow Card (Disability Worker Screening)'), ('police_check', 'National Police Check'), ('ndis_orientation', 'NDIS Orientation Certificate'), ('first_aid', 'First Aid Certificate'), ('cpr_certificate', 'CPR Certificate'), ('public_liability', 'Public Liability Insurance'), ('professional_indemnity', 'Professional Indemnity Insurance'), ('car_insurance', 'Car Insurance'), ('drivers_licence_front', "Driver's Licence (Front)"), ('drivers_licence_back', "Driver's Licence (Back)"), ('car_registration', 'Car Registration'), ('right_to_work', 'Right to Work Check'), ('service_agreement', 'Signed Service Agreement')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('has_expiry', models.BooleanField(default=True)),
                ('max_file_size_mb', models.IntegerField(default=5)),
                ('allowed_extensions', models.CharField(default='pdf,jpg,jpeg,png', help_text='Comma-separated list of allowed file extensions', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('not_started', 'Not Started'), ('personal_details', 'Personal Details'), ('documents_upload', 'Documents Upload'), ('admin_review', 'Admin Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='not_started', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('personal_details_completed_at', models.DateTimeField(blank=True, null=True)),
                ('documents_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onboarding Progress',
            },
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('abn_number', models.CharField(blank=True, help_text='Australian Business Number', max_length=20, null=True)),
                ('tfn_number', models.CharField(blank=True, help_text='Tax File Number', max_length=20, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_bsb', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or rejection reasons', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.documenttype')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
